### ISSUE TITLE
the_subtitle logic check

### ISSUE THREAD

**Issue by davidsherlock** [wecobble/Subtitles#92]
I am using the following code in my theme:

```
if ( function_exists( 'the_subtitle' ) ) {
	the_subtitle( '<p class="entry-subtitle">', '</p>' );
}
```
However this dosen't take into account if the subtitle actually exists (i.e. contains data), is there a function or way of checking this before processing other than checking the post meta?

**Comment by philiparthurmoore** [comment]
Hi David. That actually takes place inside of the plugin already. Nothing should ever return to the screen unless the post meta exists. Are you seeing otherwise?

Philip Arthur Moore
CEO @ Professional Themes (https://professionalthemes.nyc/)
philip@professionalthemes.nyc
Facebook (https://www.facebook.com/ProThemesNYC/) / Twitter (https://twitter.com/ProThemesNYC) / Press Build (https://pressbuild.blog/)
US: +1-832-632-7465 (tel:+1-832-632-7465)
VN: +84-0169-525-7591 (tel:+84-0169-525-7591)
